import { createElement } from 'lwc';
import Pc2NonPrimitiveChild from 'c/pc2NonPrimitiveChild';

describe('c-pc2-non-primitive-child', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-pc2-non-primitive-child', {
            is: Pc2NonPrimitiveChild
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});