public class Loop_assigment {

    public void forLoops(integer n){
        for (Integer  i=1; i<=n; i++) {
            System.debug(i);
            
        }
    }
    public void printEven(Integer startInt, Integer endInt){

        for (integer  i=1; i<=100; i++) {
            Integer rmn = math.mod(i, 2);
            if (rmn==0) {
            System.debug(i);
            }
            
            
        }
    }
}
